name: project build and deploy with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AWS_EC2_IP }} 
          username: ${{ secrets.AWS_EC2_USER }} 
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }} 
          port: ${{ secrets.AWS_EC2_PORT }} 
          script: | 
            cd /home/ubuntu/repo/runnerpia
            git checkout main
            git pull origin main
            /opt/gradle/gradle-8.2.1/bin/gradle build 
            if lsof -Pi :$8080 -sTCP:LISTEN -t >/dev/null; then
              echo "8080 포트가 사용 중입니다. 프로세스를 종료합니다."
              sudo fuser -k $8080/tcp
            else
              echo "8080 포트는 사용 중이지 않습니다."
            fi
            nohup java -jar ./build/libs/*.jar >> "../../logs/runnerpia/runnerpia_$(date +'%Y%m%d').log" 2>&1 &
